### ISSUE TITLE
Error when import SubEdit

### ISSUE THREAD

**Issue by locsucc** [deadYokai/dishonored-toolkit#3]
**i got this error when i import upk from yaml using SubEdit**
![image](https://github.com/deadYokai/dishonored-toolkit/assets/171554153/2c41e1a3-8f5f-415f-9e55-bb24cc52c5e8)

**Comment by deadYokai** [comment]
> **i got this error when i import upk from yaml using SubEdit** ![image](https://private-user-images.githubusercontent.com/171554153/344556695-2c41e1a3-8f5f-415f-9e55-bb24cc52c5e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MTQ1NzMsIm5iZiI6MTcxOTgxNDI3MywicGF0aCI6Ii8xNzE1NTQxNTMvMzQ0NTU2Njk1LTJjNDFlMWEzLThmNWYtNDE1Zi05ZTU1LWJiMjRjYzUyYzVlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMVQwNjExMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTFjZjMyYTg1M2JjYWIxMTA2MDQ2NWE1ZGIyZGJmNzA3ZjhlMjE0MDU4NTEwODE2ZDA1ZWUxMjIzYzdlZDkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wzpKvxGY-HbMu914A4GhdN9CwfH83-rTHrB-cEFeoCU)

List your actions in order

**Comment by locsucc** [comment]
wdym?

**Comment by deadYokai** [comment]
> wdym?

how to reproduce? step by step

**Comment by locsucc** [comment]
https://streamable.com/fznggs

**Comment by deadYokai** [comment]
> [streamable.com/fznggs](https://streamable.com/fznggs)

you need to specify a lang to replace `--langCode`

**Comment by locsucc** [comment]
> > [streamable.com/fznggs](https://streamable.com/fznggs)
> 
> you need to specify a lang to replace `--langCode`

still crash ;-; i tried INT

**Comment by deadYokai** [comment]
> > > [streamable.com/fznggs](https://streamable.com/fznggs)
> > 
> > 
> > you need to specify a lang to replace `--langCode`
> 
> still crash ;-; i tried INT

from README
> `--langCode` - Language to replace (except **INT**, because i'm too lazy :P)

**Comment by deadYokai** [comment]
i added INT support, but i haven't tested it: fe9f6730ec2e2a6e28b417307bf6cf3492bd57b8

**Comment by locsucc** [comment]
i tried another lang code (RUS) but still dont work, i got stuck on loading through

**Comment by deadYokai** [comment]
> i tried another lang code (RUS) but still dont work, i got stuck on loading through

you can try replace subtitles (INT) with [UPK Explorer](https://www.nexusmods.com/site/mods/587)
and check a upk file if it has errors

**Comment by locsucc** [comment]
error!! when trying INT
![image](https://github.com/deadYokai/dishonored-toolkit/assets/171554153/df323f33-3ef6-4761-9844-a65e39c76229)

**Comment by deadYokai** [comment]
> error!! when trying INT ![image](https://private-user-images.githubusercontent.com/171554153/344734266-df323f33-3ef6-4761-9844-a65e39c76229.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4NTc1ODAsIm5iZiI6MTcxOTg1NzI4MCwicGF0aCI6Ii8xNzE1NTQxNTMvMzQ0NzM0MjY2LWRmMzIzZjMzLTNlZjYtNDc2MS05ODQ0LWE2NWUzOWM3NjIyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMVQxODA4MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZDYxMTk5ZmM0Mjg1YTUxZmY2Y2VkYjUwMjZjYzVhNGJlYjM2MTJhZmEwYTM0OTNjM2VlNGUzZDRiODBhMjI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7vhs0zpDyUppyaUhPUlThWJQyKwy5SmNaixBdF33DKE)

try with `--langReplace` for ex. `--langCode ESN --langReplace ESN`

**Comment by locsucc** [comment]
nope
![image](https://github.com/deadYokai/dishonored-toolkit/assets/171554153/0e569eb0-98ab-471d-8432-19a7b59c8573)

**Comment by deadYokai** [comment]
> nope ![image](https://private-user-images.githubusercontent.com/171554153/344852645-0e569eb0-98ab-471d-8432-19a7b59c8573.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4OTQzNzksIm5iZiI6MTcxOTg5NDA3OSwicGF0aCI6Ii8xNzE1NTQxNTMvMzQ0ODUyNjQ1LTBlNTY5ZWIwLTk4YWItNDcxZC04NDMyLTE5YTdiNTljODU3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMlQwNDIxMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjdlMzM4ZmJkNDU4OTFlZDkxYjcyY2Q2MmM2ZDY0OThkYTAwZDE4YTEwNDc4ODNiNzk1MGE0NjA1YmY5YmJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VuKWO3zFAH-kr9MVVTQAQlYgAETapCajI-Dd4tyvY1A)

try 84884d136c058f2ca17cf1ec238cf7b697a98d3a

**Comment by locsucc** [comment]
worked perfectly
![image](https://github.com/deadYokai/dishonored-toolkit/assets/171554153/fa61e6ee-3250-4586-bb77-5b5aadaf84bb)

**Comment by locsucc** [comment]
**but the subtitle packer dont work when i localize some text to vietnamese**

Traceback (most recent call last):
  File "C:\Users\locsucc\AppData\Local\Programs\Python\Python312\Lib\site-packages\yaml\reader.py", line 89, in peek
    return self.buffer[self.pointer+index]
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
IndexError: string index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\locsucc\Downloads\dishonored-toolkit-main\subedit.py", line 301, in <module>
    packYaml(fp, args.input, args.langCode, args.langReplace)
  File "C:\Users\locsucc\Downloads\dishonored-toolkit-main\subedit.py", line 181, in packYaml
    yod = yaml.load(yf, Loader=yaml.SafeLoader)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\locsucc\AppData\Local\Programs\Python\Python312\Lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\locsucc\AppData\Local\Programs\Python\Python312\Lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\locsucc\AppData\Local\Programs\Python\Python312\Lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\locsucc\AppData\Local\Programs\Python\Python312\Lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\locsucc\AppData\Local\Programs\Python\Python312\Lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\locsucc\AppData\Local\Programs\Python\Python312\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\locsucc\AppData\Local\Programs\Python\Python312\Lib\site-packages\yaml\composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\locsucc\AppData\Local\Programs\Python\Python312\Lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
                         ^^^^^^^^^^^^
  File "C:\Users\locsucc\AppData\Local\Programs\Python\Python312\Lib\site-packages\yaml\parser.py", line 449, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\locsucc\AppData\Local\Programs\Python\Python312\Lib\site-packages\yaml\scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "C:\Users\locsucc\AppData\Local\Programs\Python\Python312\Lib\site-packages\yaml\scanner.py", line 255, in fetch_more_tokens
    return self.fetch_plain()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\locsucc\AppData\Local\Programs\Python\Python312\Lib\site-packages\yaml\scanner.py", line 679, in fetch_plain
    self.tokens.append(self.scan_plain())
                       ^^^^^^^^^^^^^^^^^
  File "C:\Users\locsucc\AppData\Local\Programs\Python\Python312\Lib\site-packages\yaml\scanner.py", line 1290, in scan_plain
    ch = self.peek(length)
         ^^^^^^^^^^^^^^^^^
  File "C:\Users\locsucc\AppData\Local\Programs\Python\Python312\Lib\site-packages\yaml\reader.py", line 91, in peek
    self.update(index+1)
  File "C:\Users\locsucc\AppData\Local\Programs\Python\Python312\Lib\site-packages\yaml\reader.py", line 153, in update
    self.update_raw()
  File "C:\Users\locsucc\AppData\Local\Programs\Python\Python312\Lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\locsucc\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 6164: character maps to <undefined>

**Comment by deadYokai** [comment]
> **but the subtitle packer dont work when i localize some text to vietnamese**

what encoding in yaml file?

**Comment by locsucc** [comment]
UTF-8

**Comment by deadYokai** [comment]
> UTF-8

try 45bc672fedd91f89f30e5cbdbd5bb5119b147d5f

**Comment by locsucc** [comment]
worked thanks bro u r god
